name: Approve pull requests securely
description: Approve pull requests securely
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: green
inputs:
  app_id:
    description: |
      GitHub App ID
    required: true
  app_private_key:
    description: |
      GitHub App Private Key
    required: true
  server_repository:
    description: |
      Server repository name
    required: true

  repository:
    description: |
      The repository name of the updated pull request
    required: false
  pull_request_number:
    description: |
      The pull request number of the updated pull request
    required: false
    default: ${{github.event.issue.number}}
runs:
  using: composite
  steps:
    # Create a GitHub App token to create and delete a label
    - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
      id: token
      with:
        app-id: ${{inputs.app_id}}
        private-key: ${{inputs.app_private_key}}
        permission-issues: write
        owner: ${{ github.repository_owner }}
        repositories: |
          ${{inputs.server_repository}}

    - uses: securefix-action/label-action@e882c05058dd13a9072a60980f490728cea7de1c # v0.1.0
      with:
        prefix: approve-pr-
        description: ${{github.repository_owner}}/${{inputs.repository && inputs.repository || github.event.repository.name}}/${{inputs.pull_request_number}}
        repository: ${{inputs.server_repository}}
        github_token: ${{steps.token.outputs.token}}
